# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    #    target-branch: "main"
    open-pull-requests-limit: 50
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
    ignore:
      - dependency-name: com.puppycrawl.tools:checkstyle
        versions:
          - ">= 10"
      - dependency-name: org.asciidoctor:asciidoctor-maven-plugin
        versions:
          - ">= 3"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Shanghai"
