stages:
  - main

main:
  stage: main
  image: maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  cache:
    paths:
      - .m2/repository
  script:
    - git --version
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -e -U package source:jar javadoc:jar install -DskipTests && echo 发布完成
  artifacts:
    paths:
      - target/chensoul-parent-*
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      changes:
        - ".mvn/**/*"
        - "src/**/*"
        - ".gitlab-ci.yml"
        - "mvnw"
        - "mvnw.cmd"
        - "pom.xml"
        - "!README.md"
