name: Release Version

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[CI Skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Apache Maven Central
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: OSS_USERNAME
          server-password: OSS_TOKEN
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Publish to Apache Maven Central
        run: mvn clean deploy --ntp --batch-mode --update-snapshots -P release -Dmaven.javadoc.skip=true -DskipTests
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_TOKEN: ${{ secrets.OSS_TOKEN }}
          # gpg短密码
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
