name: SonarCloud

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    if: github.repository_owner == 'chensoul'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: zulu
      - name: Analyze with SonarCloud
        run: ./mvnw verify sonar:sonar -B -Dsonar.projectKey=chensoul_parent -Dsonar.organization=chensoul -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -ntp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}